[project]
name = "pyquant-research-report-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.1.1",
    "llama-index>=0.12.17",
    "python-dotenv>=1.0.1",
    "tavily-python>=0.5.1",
]
